version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    steps:
      - checkout
      - run: go build
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
         command: |
           go test -cover -coverprofile=coverage.out ./...
           go tool cover -html=coverage.out -o coverage.html
           mv coverage.html /tmp/artifacts
           cat coverage.out >> coverage.txt
      - store_artifacts:
         path: /tmp/artifacts
      - codecov/upload:
          file: coverage.txt